### ISSUE TITLE
After upgrading testnet node getting error complaining ini file is not defined

### ISSUE THREAD

**Issue by Fez29** [loki-project/loki-launcher#34]
Existing instance on testnet running loki-launcher.

Steps taken:
1)
sudo npm i -g loki-launcher
2)
loki-launcher download-binaries --testnet
3)
loki-launcher status

Response:
___________________

~$ loki-launcher client
/usr/lib/node_modules/loki-launcher/config.js:160
      const moneroDiskOptions = ini.iniToJSON(moneroDiskConfig.toString())
                                ^

ReferenceError: ini is not defined
    at loadBlockchainConfigFile (/usr/lib/node_modules/loki-launcher/config.js:160:33)
    at precheckConfig (/usr/lib/node_modules/loki-launcher/config.js:210:3)
    at Object.checkConfig [as check] (/usr/lib/node_modules/loki-launcher/config.js:437:3)
    at Object.<anonymous> (/usr/lib/node_modules/loki-launcher/index.js:89:12)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
___________________

I am passing testnet flags via ~/.loki/loki.conf

Please let me know if above is not sufficient and more details/logfiles etc are required or incorrect steps followed.

**Comment by neuroscr** [comment]
in config.js (in /usr/lib/node_modules/loki-launcher)
add this to the top of the file
```
const ini = require(__dirname + '/ini')
```

**Comment by Fez29** [comment]
It is now working and active :)
![image](https://user-images.githubusercontent.com/41666396/60371774-93ad6980-99fa-11e9-95a4-c95d02b3f1f7.png)

**Comment by Fez29** [comment]
As requested on TG service nodes channel @neuroscr 

~$ loki-launcher config-view
parsed loki config { 'rpc-bind-port': '22024', testnet: true }

        .o0l.
       ;kNMNo.
     ;kNMMXd'
   ;kNMMXd'                 .ld:             ,ldxkkkdl,.     'dd;     ,odl.  ;dd
 ;kNMMXo.  'ol.             ,KMx.          :ONXkollokXN0c.   cNMo   .dNNx'   dMW
dNMMM0,   ;KMMXo.           ,KMx.        .oNNx'      .dNWx.  :NMo .cKWk;     dMW
'dXMMNk;  .;ONMMXo'         ,KMx.        :NMx.         oWWl  cNWd;ON0:.      oMW
  'dXMMNk;.  ;kNMMXd'       ,KMx.        lWWl          :NMd  cNMNNMWd.       dMW
    'dXMMNk;.  ;kNMMXd'     ,KMx.        :NMx.         oWWl  cNMKolKWO,      dMW
      .oXMMK;   ,0MMMNd.    ,KMx.        .dNNx'      .dNWx.  cNMo  .dNNd.    dMW
        .lo'  'dXMMNk;.     ,KMXxdddddl.   :ONNkollokXN0c.   cNMo    ;OWKl.  dMW
            'dXMMNk;        .lddddddddo.     ,ldxkkkdl,.     'od,     .cdo;  ;dd
          'dXMMNk;
         .oNMNk;             L A U N C H E R   v e r s i o n   v 0 . 8
          .l0l.

loki-launcher is in /usr/lib/node_modules/loki-launcher
Launcher stored-config: { type: 'etc',
  launcher:
   { interface: false,
     var_path: '/opt/loki-launcher/var',
     network: 'test' },
  blockchain:
   { data_dir: '/home/snode/.loki',
     data_dir_is_default: true,
     network: 'test',
     binary_path: '/opt/loki-launcher/bin/lokid',
     rpc_port: 38157,
     rpc_ip: '127.0.0.1' },
  network: { enabled: false },
  storage:
   { enabled: true,
     binary_path: '/opt/loki-launcher/bin/loki-storage',
     data_dir: '/home/snode/.loki/storage',
     data_dir_is_default: true,
     port: 8080 } }
Launcher running-config: { type: 'etc',
  launcher:
   { interface: false,
     var_path: '/opt/loki-launcher/var',
     network: 'test',
     docker: true,
     publicIPv4: '51.79.43.168' },
  blockchain:
   { data_dir: '/home/snode/.loki',
     data_dir_is_default: true,
     network: 'test',
     binary_path: '/opt/loki-launcher/bin/lokid',
     rpc_port: 38157,
     rpc_ip: '127.0.0.1' },
  network:
   { enabled: false,
     auto_config_test_ips: [ '1.1.1.1', '8.8.8.8' ],
     auto_config_test_host: 'www.imdb.com',
     auto_config_test_port: 80,
     binary_path: '/usr/local/bin/lokinet',
     rpc_ip: '127.0.0.1',
     rpc_port: 0,
     lokid:
      { data_dir: '/home/snode/.loki',
        data_dir_is_default: true,
        network: 'test',
        binary_path: '/opt/loki-launcher/bin/lokid',
        rpc_port: 38157,
        rpc_ip: '127.0.0.1' } },
  storage:
   { enabled: true,
     binary_path: '/opt/loki-launcher/bin/loki-storage',
     data_dir: '/home/snode/.loki/storage',
     data_dir_is_default: true,
     port: 8080,
     lokid_key: '/home/snode/.loki/testnet/key',
     lokid_rpc_port: 38157,
     ip: '192.168.100.113' } }

**Comment by Fez29** [comment]
Here is print_sn_status response

print_sn_status
FROM SOCKET: Service Node Registration State [1]
    [0] Service Node: 1871c2e88b81ca914b4db60c4390baec650a508d0b54f54e680266fc495269d3
        Total Contributed/Staking Requirement: 100.000000000/100.000000000
        Total Reserved: 100.000000000
        Register/Expiry Height: Staking Infinitely (stake unlock not requested yet)
        Last Reward At (Height/TX Index): 75568/4294967295
        Operator Cut (% Of Reward): 100.00%
        Operator Address: T6TVaHjcd58PjgtUm4bbdfhmAqJaWVmVAXaieVsgWjqfeYEFpfUp1446ScVaLTyZdP7d3JSdohpK4LKEUHj2hKaG2zZm6GHgn
        Last Uptime Proof Received: Not Received Yet
        Current Status: DECOMMISSIONED
        Remaining Decommission Time Until DEREGISTRATION: -262 blocks

        [0] Contributor: T6TVaHjcd58PjgtUm4bbdfhmAqJaWVmVAXaieVsgWjqfeYEFpfUp1446ScVaLTyZdP7d3JSdohpK4LKEUHj2hKaG2zZm6GHgn
            Amount / Reserved: 100.000000000/100.000000000

**Comment by Fez29** [comment]
@neuroscr 

I came across something a bit odd regarding lokiKey,

When I stop Loki-launcher and then start it again, it show that the lokiKey has been found at ~/.loki........

Then after a couple seconds when I ask for status, it says it is offline,

![image](https://user-images.githubusercontent.com/41666396/60381954-4b269800-9a5c-11e9-96de-a4db5937a7db.png)


To add to that it appears my config inside loki.conf is being ignored in regards to the rpc-bind-port that I have set inside it, tried putting the file in, 

~/.loki 
~/.loki/testnet/

same behaviour

**Comment by neuroscr** [comment]
Fixed in 0.0.10
