### ISSUE TITLE
Version Flags

### ISSUE THREAD

**Issue by jpthor** [loki-project/loki-launcher#52]
### Current:

```
loki-launcher -v
loki-launcher --version
```

are unknown flags. 

### Desired:

Spit out versions

## 2. ASCII ART Version

Doesn't update the loki-launcher version

![image](https://user-images.githubusercontent.com/41815753/62014513-323d0e00-b1e5-11e9-9632-d6704c4fbfa7.png)

**Comment by BeaudanBrown** [comment]
The ascii art version is correct I believe
The previous version was 0.0.14

**Comment by neuroscr** [comment]
already talked to JP over tg
